// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkeGqXMcWe4JsXhgJnZK2G0JlnCa1LfjY',
    appId: '1:580076762827:web:192258e67885e123dbcd4e',
    messagingSenderId: '580076762827',
    projectId: 'group-leaderboard-a8d51',
    authDomain: 'group-leaderboard-a8d51.firebaseapp.com',
    storageBucket: 'group-leaderboard-a8d51.firebasestorage.app',
    measurementId: 'G-DFP97JTK6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACwkrfCJjAzxOx_ZJ4PaDDLWIid-9JFxo',
    appId: '1:580076762827:android:258877b2f5e479b1dbcd4e',
    messagingSenderId: '580076762827',
    projectId: 'group-leaderboard-a8d51',
    storageBucket: 'group-leaderboard-a8d51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhO-AnOpTB_mqE_rv5BrFxeRL-f1WRuLM',
    appId: '1:580076762827:ios:51c0ea2b7716c755dbcd4e',
    messagingSenderId: '580076762827',
    projectId: 'group-leaderboard-a8d51',
    storageBucket: 'group-leaderboard-a8d51.firebasestorage.app',
    iosBundleId: 'com.example.groupLeaderboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhO-AnOpTB_mqE_rv5BrFxeRL-f1WRuLM',
    appId: '1:580076762827:ios:51c0ea2b7716c755dbcd4e',
    messagingSenderId: '580076762827',
    projectId: 'group-leaderboard-a8d51',
    storageBucket: 'group-leaderboard-a8d51.firebasestorage.app',
    iosBundleId: 'com.example.groupLeaderboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkeGqXMcWe4JsXhgJnZK2G0JlnCa1LfjY',
    appId: '1:580076762827:web:07ac3f5b7812e400dbcd4e',
    messagingSenderId: '580076762827',
    projectId: 'group-leaderboard-a8d51',
    authDomain: 'group-leaderboard-a8d51.firebaseapp.com',
    storageBucket: 'group-leaderboard-a8d51.firebasestorage.app',
    measurementId: 'G-3BKPMD0QSC',
  );
}
